SELECT N_NAME, SUM(L_QUANTITY) AS C
FROM LINEITEM, ORDERS, NATION, CUSTOMER 
WHERE L_ORDERKEY = O_ORDERKEY AND O_CUSTKEY = C_CUSTKEY AND C_NATIONKEY = N_NATIONKEY               
GROUP BY N_NAME 
HAVING C > 62000
ORDER BY C DESC;